config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  devise_for :users

  root to: 'static_pages#home'

  get '/produtos' => 'static_pages#products'
  get '/servicos' => 'static_pages#services'
  get '/conteudos' => 'static_pages#content'
  get '/sobre-nos' => 'static_pages#about_us'
  get '/contato' => 'static_pages#contact'

  resources :members
  resources :jobs
  resources :banners
  resources :tech_products
  resources :case_products

  get 'subscribers/export' => 'subscribers#export'

  resources :subscribers
end

app/models/banner.rb
class Banner < ApplicationRecord
  has_attachment :image, accept: [:jpg, :png, :gif]
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_banner, only: [:show, :edit, :update, :destroy]

  # GET /banners
  # GET /banners.json
  def index
    @banners = Banner.all
  end

  # GET /banners/1
  # GET /banners/1.json
  def show
  end

  # GET /banners/new
  def new
    @banner = Banner.new
  end

  # GET /banners/1/edit
  def edit
  end

  # POST /banners
  # POST /banners.json
  def create
    @banner = Banner.new(banner_params)

    respond_to do |format|
      if @banner.save
        format.html { redirect_to banners_path, notice: 'O banner foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @banner }
      else
        format.html { render :new }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banners/1
  # PATCH/PUT /banners/1.json
  def update
    respond_to do |format|
      if @banner.update(banner_params)
        format.html { redirect_to banners_path, notice: 'O banner foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @banner }
      else
        format.html { render :edit }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banners/1
  # DELETE /banners/1.json
  def destroy
    @banner.destroy
    respond_to do |format|
      format.html { redirect_to banners_url, notice: 'O banner foi excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_banner
      @banner = Banner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def banner_params
      params.require(:banner).permit(:image, :link)
    end
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/views/banners/_form.html.erb
<%= form_with(model: banner, local: true) do |form| %>
  <% if banner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(banner.errors.count, "error") %> prohibited this banner from being saved:</h2>

      <ul>
      <% banner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.attachinary_file_field :image %>
  </div>

  <div class="form-group">
    <%= form.label :link %>
    <%= form.text_field :link, id: :job_link, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-success' %>
  </div>

  <br>
<% end %>

app/views/banners/edit.html.erb
<%= render 'layouts/admin_navbar' %>

<div class="container">
  <h1>Editar Banner</h1>

  <%= render 'form', banner: @banner %>

  <%= link_to 'Voltar', banners_path, class: 'btn btn-secondary' %>
</div>

app/views/banners/index.html.erb
<%= render 'layouts/admin_navbar' %>

<div class="container">
  <% if notice %>
    <div class="alert alert-success">
      <%= notice %>
    </div>
  <% end %>
  
  <% if @banners.empty? %>
    <div class="alert alert-info">
      Não há banners.
    </div>
  <% else %>
    <div class="row pb-4">
      <% @banners.each do |banner| %>
        <div class="col-md-4">
          <div style="border: 1px solid #dcdcdc">
            <%= cl_image_tag banner.image.path, width: '100%' %>
          </div>
          <br>
          <%= link_to "Editar", edit_banner_path(banner), class: 'btn btn-outline-primary' %>
          <%= link_to "Excluir", banner_path(banner), method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn btn-outline-danger' %>
        </div>
      <% end %>
    </div>
  <% end %>

  <%= link_to 'Novo banner', new_banner_path, class: 'btn btn-success' %>
</div>

app/views/banners/new.html.erb
<%= render 'layouts/admin_navbar' %>

<div class="container">
  <h1>Novo Banner</h1>

  <%= render 'form', banner: @banner %>

  <%= link_to 'Voltar', banners_path, class: 'btn btn-secondary' %>
</div>

app/views/banners/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_banner_path(@banner) %> |
<%= link_to 'Back', banners_path %>