config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  devise_for :users

  root to: 'static_pages#home'

  get '/produtos' => 'static_pages#products'
  get '/servicos' => 'static_pages#services'
  get '/conteudos' => 'static_pages#content'
  get '/sobre-nos' => 'static_pages#about_us'
  get '/contato' => 'static_pages#contact'

  resources :members
  resources :jobs
  resources :banners
  resources :tech_products
  resources :case_products

  get 'subscribers/export' => 'subscribers#export'

  resources :subscribers
end

app/models/case_product.rb
class CaseProduct < ApplicationRecord
  has_many :case_product_descriptions, inverse_of: :case_product

  enum color: [:green, :blue, :light_blue, :orange, :red]
  
  has_attachment :image, accept: [:jpg, :png, :gif]

  accepts_nested_attributes_for :case_product_descriptions, allow_destroy: true
end

app/controllers/case_products_controller.rb
class CaseProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_case_product, only: [:show, :edit, :update, :destroy]

  # GET /case_products
  # GET /case_products.json
  def index
    @case_products = CaseProduct.all
  end

  # GET /case_products/1
  # GET /case_products/1.json
  def show
  end

  # GET /case_products/new
  def new
    @case_product = CaseProduct.new
  end

  # GET /case_products/1/edit
  def edit
  end

  # POST /case_products
  # POST /case_products.json
  def create
    @case_product = CaseProduct.new(case_product_params)

    respond_to do |format|
      if @case_product.save
        format.html { redirect_to @case_product, notice: 'Case product was successfully created.' }
        format.json { render :show, status: :created, location: @case_product }
      else
        format.html { render :new }
        format.json { render json: @case_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /case_products/1
  # PATCH/PUT /case_products/1.json
  def update
    respond_to do |format|
      if @case_product.update(case_product_params)
        format.html { redirect_to @case_product, notice: 'Case product was successfully updated.' }
        format.json { render :show, status: :ok, location: @case_product }
      else
        format.html { render :edit }
        format.json { render json: @case_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /case_products/1
  # DELETE /case_products/1.json
  def destroy
    @case_product.destroy
    respond_to do |format|
      format.html { redirect_to case_products_url, notice: 'Case product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_case_product
      @case_product = CaseProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def case_product_params
      params.require(:case_product).permit(
        :category, :name, :description, :link,
        :color, :image, :image_height,
        case_product_descriptions_attributes: [:id, :position, :name, :description, :_destroy]
      )
    end
end

app/helpers/case_products_helper.rb
module CaseProductsHelper
end

app/views/case_products/_case_product_description_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :position %>
        <%= f.number_field :position, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <%= link_to_remove_association "Remover descrição", f, class: 'btn btn-danger' %>

  <hr class="divider">
</div>

app/views/case_products/_form.html.erb
<%= form_with(model: case_product, local: true) do |form| %>
  <% if case_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(case_product.errors.count, "error") %> prohibited this case_product from being saved:</h2>

      <ul>
      <% case_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :category %>
    <%= form.text_field :category, id: :case_product_category, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :case_product_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :case_product_description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :link %>
    <%= form.text_field :link, id: :case_product_link, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :color %>
    <%= form.select :color, CaseProduct.colors.map { |c| [c.first, c.first] }, {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.attachinary_file_field :image %>
  </div>

  <div class="form-group">
    <%= form.label :image_height %>
    <%= form.number_field :image_height, id: :case_product_image_height, class: 'form-control' %>
  </div>

  <hr class="divider">

  <h3>Descrições</h3>

  <div id='case_product_descriptions'>
    <%= form.fields_for :case_product_descriptions do |case_product_description| %>
      <%= render 'case_product_description_fields', f: case_product_description %>
    <% end %>

    <div class='links pb-3'>
      <%= link_to_add_association 'Adicionar descrição', form, :case_product_descriptions, class: 'btn btn-primary' %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-success" %>
  </div>

  <br>
<% end %>

<script>
  $('textarea').each(function() {
    var simplemde = new SimpleMDE({
      element: this,
      spellChecker: false
    });

    simplemde.render(); 
  })
</script>

app/views/case_products/edit.html.erb
<%= render 'layouts/admin_navbar' %>

<div class="container">
  <h1>Editar Case/Aplicação</h1>

  <%= render 'form', case_product: @case_product %>

  <%= link_to 'Voltar', case_products_path, class: 'btn btn-secondary' %>
</div>

app/views/case_products/index.html.erb
<%= render 'layouts/admin_navbar' %>

<div class="container">
  <% if notice %>
    <div class="alert alert-success">
      <%= notice %>
    </div>
  <% end %>
  
  <% if @case_products.empty? %>
    <div class="alert alert-info">
      Não há cases e aplicações.
    </div>
  <% else %>
    <table class="table">
      <thead>
        <tr>
          <th>Categoria</th>
          <th>Nome</th>
          <th>Descrição</th>
          <th>Link</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @case_products.each do |case_product| %>
          <tr>
            <td><%= case_product.category %></td>
            <td><%= case_product.name %></td>
            <td><%= case_product.description.truncate(50) %></td>
            <td><%= link_to "Link", case_product.link %></td>
            <td><%= link_to 'Exibir', case_product %></td>
            <td><%= link_to 'Editar', edit_case_product_path(case_product) %></td>
            <td><%= link_to 'Excluir', case_product, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

  <%= link_to 'Novo case/aplicação', new_case_product_path, class: "btn btn-success" %>
</div>

app/views/case_products/new.html.erb
<%= render 'layouts/admin_navbar' %>

<div class="container">
  <h1>Novo Case/Aplicação</h1>

  <%= render 'form', case_product: @case_product %>

  <%= link_to 'Voltar', case_products_path, class: 'btn btn-secondary' %>
</div>

app/views/case_products/show.html.erb
<%= render 'layouts/admin_navbar' %>

<div class="container">
  <% if notice %>
    <div class="alert alert-success">
      <%= notice %>
    </div>
  <% end %>
</div>

<div class="solutions pt-0">
  <div class="content container">
    <div class="solutions-wrapper">
      <div class="solution pb-4">
        <div class="title">
          <%= @case_product.category %>
        </div>

        <div class="d-none d-lg-block">
          <%= cl_image_tag @case_product.image.path, height: "#{@case_product.image_height}px" %>
        </div>

        <div class="d-block d-lg-none">
          <%= cl_image_tag @case_product.image.path, width: '100%', height: 'auto' %>
        </div>

        <div class="short-description">
          <%= markdown(@case_product.description) %>
        </div>

        <div class="row points">
          <% @case_product.case_product_descriptions.each do |point| %>
            <div class="col-md-6">
              <div class="point">
                <div class="title">
                  <strong><%= point.name %></strong>
                </div>
                
                <div class="description">
                  <%= markdown(point.description) %>
                </div>
              </div>
            </div>
          <% end %>
        </div>

        <div class="actions text-center">
          <a href="<%= @case_product.link %>" class="btn btn-outline-<%= @case_product.color.gsub("_", "-") %>">
            Veja mais sobre o <strong><%= @case_product.name %></strong>
            <span>&nbsp;</span>
            <%= fa_icon "chevron-right" %>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

<hr class="divider">

<div class="container pt-2">
  <%= link_to "Editar", edit_case_product_path, class: "btn btn-primary" %>
  <span>&nbsp;</span>
  <%= link_to "Voltar", case_products_path, class: "btn btn-secondary" %>
</div>